### ISSUE TITLE
Code Smells

### ISSUE THREAD

**Issue by leandroohsr** [leandroohsr/MC656#40]

**Comment by leandroohsr** [comment]
Code Smell 1 - Dispensable - Removendo comentários e imports não usados no código

**Comment by arturrur** [comment]
Code Smell 2 - Bloater - Estávamos escrevendo os eventos das olimpíadas todos no próprio arquivo .tsx , passamos todos os eventos para um arquivo .csv e o integramos na página de calendário por meio de um parsing do csv.

**Comment by henriquemmartim** [comment]
Code Smell 3 - Bloater - O código funcional do timer está fazendo diversas coisas, portanto, estamos separando em métodos.
