### ISSUE TITLE
Casos de Teste

### ISSUE THREAD

**Issue by henriquemmartim** [leandroohsr/MC656#47]
Casos de teste para Avaliação 5

**Comment by arturrur** [comment]
Critérios para os testes da RegisterPage: [Teste da RegisterPage.pdf](https://github.com/user-attachments/files/15934649/Classes.de.Equivalencia-.RegisterPage.1.pdf)


Arquivos dos testes:
src/tests/register1.spec.tsx
src/tests/register2.spec.tsx
src/tests/register3.spec.tsx
src/tests/register4.spec.tsx
src/tests/register5.spec.tsx
src/tests/register6.spec.tsx
src/tests/register7.spec.tsx
src/tests/register8.spec.tsx
src/tests/register9.spec.tsx
src/tests/register10.spec.tsx

Print do teste realizado:
![image](https://github.com/leandroohsr/MC656/assets/127426928/8e5430f7-f8f3-44a7-b222-74fa35db573d)

**Comment by henriquemmartim** [comment]
Critérios para os testes do TimerPage:
[Teste do Timer.pdf](https://github.com/user-attachments/files/15934656/Teste.do.Time.1.pdf)


Arquivos dos testes:
src/tests/timer1.spec.tsx
src/tests/timer2.spec.tsx
src/tests/timer3.spec.tsx

Print do teste realizado:
![image](https://github.com/leandroohsr/MC656/assets/127907494/b4fc1f9a-bad2-429e-840f-0c607a2d1c70)

**Comment by henriquemmartim** [comment]
Critérios para os testes do CalendarioPage:
[Teste do Calendario.pdf](https://github.com/user-attachments/files/15934668/Teste.do.Calendario.1.pdf)


Arquivos dos testes:
src/tests/calendar1.spec.tsx
src/tests/calendar2.spec.tsx
src/tests/calendar3.spec.tsx

print dos testes:
![image](https://github.com/leandroohsr/MC656/assets/127426928/379ace35-19e4-4ab2-ada7-4ee1c339d209)

**Comment by arturrur** [comment]
Finalizado
